=== WescleyPlinio/pos-2025-tarefas/xml/definicoes.dtd
<!ELEMENT cardapio (prato+)>
<!ELEMENT prato (nome, descricao, ingredientes, preco, calorias, tempoPreparo)>
<!ATTLIST prato id ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT tempoPreparo (#PCDATA)>

=== WescleyPlinio/pos-2025-tarefas/xml/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">
<cardapio>
    <prato id="c1"> 
        <nome>
            Risoto
        </nome>
        <descricao>
            Arroz soltinho 
        </descricao>
        <ingredientes>
            Arroz, cenoura, alho e frango
        </ingredientes>
        <preco>
            15
        </preco>
        <calorias>
            2050
        </calorias>
        <tempoPreparo>
            20min
        </tempoPreparo>
    </prato>
    <prato id="c2"> 
        <nome>
            Feijoada
        </nome>
        <descricao>
            Feijoada feita por Cirilo em pessoa. 
        </descricao>
        <ingredientes>
            Feijão preto, verduras, batatinha e calabreso
        </ingredientes>
        <preco>
            25
        </preco>
        <calorias>
            120
        </calorias>
        <tempoPreparo>
            30min
        </tempoPreparo>
    </prato>
    <prato id="c3"> 
        <nome>
            Lasanha
        </nome>
        <descricao>
            Lasanha feita por Cirilo em pessoa. 
        </descricao>
        <ingredientes>
            Macarrão de lasanha, carne, queijo, carne, tomate e muito amor
        </ingredientes>
        <preco>
            50
        </preco>
        <calorias>
            320
        </calorias>
        <tempoPreparo>
            60min
        </tempoPreparo>
    </prato>
    <prato id="c4"> 
        <nome>
            Pudim
        </nome>
        <descricao>
            Pudim criado por Cirilo e Fernanda, em homenagem a Ari.
        </descricao>
        <ingredientes>
            Leite moça, açucar e camaradagem
        </ingredientes>
        <preco>
            amizade não tem valor.
        </preco>
        <calorias>
            muitas
        </calorias>
        <tempoPreparo>
            10min
        </tempoPreparo>
    </prato>
    <prato id="c5"> 
        <nome>
            Macarrão
        </nome>
        <descricao>
            Carlinhos comeu 2050 
        </descricao>
        <ingredientes>
            Macarrão, alho, cebola, Carlinhos
        </ingredientes>
        <preco>
            2050
        </preco>
        <calorias>
            2050
        </calorias>
        <tempoPreparo>
            2050min
        </tempoPreparo>
    </prato>
</cardapio>
